categories:
- Data Managers
description: Builds a blastn database from a history FASTA or a data table entry.
homepage_url: ''
long_description: ''
name: data_manager_make_blastn_dbs
owner: dave
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_fetch_genome_dbkeys_all_fasta
type: unrestricted
