categories:
- Data Managers
description: Builds a blastn database from a history FASTA or a data table entry.
homepage_url: ''
long_description: ''
name: data_manager_blastn_database_builder
owner: test
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_blastn_database_builder
type: unrestricted
